### PR TITLE
Move azurerm to azure, add providers example

### PR DESCRIPTION
**Pull request by teszes**

### CODE REVIEW

**Comment by sanyer** [comment]
What's the reasoning behind the renaming azurerm to azure @teszes ?

**Comment by teszes** [comment]
The provider azurerm is one of four providers covering Azure stuff. There is three others, and they use resources which are interconnected with azurerm's. So for example to register a managed identitiy in Azure AD for a VM created w/ azurerm, you would use the azuread provider's resources. So they are separate, but tightly coupled. There are no such connections between other provider that I know of. Also, TF actually aliases the azure provider to azurerm, so if it introduces confusion, it resolves itself automatically.

**Comment by teszes** [comment]
So to be clear, you need to provide azurerm resources as params to azuread resources for example.

The other two providers are azurestack for Stack, which is on-prem Azure, and azuredevops, which I think is obvious.

**Comment by sanyer** [comment]
Ok. And you plan to put examples of all of these providers?

**Comment by teszes** [comment]
Yes, that's right. Plan is to work up to LAnding Zones, reference architectures created by Microsoft, which would bring a lot of value in my opiniton, and we could use them directly for projects

**Review by sanyer — APPROVED** [review]

**Pull request merged**
