### PR TITLE
Universal bin/apply* bin/destroy* scripts

### PR DESCRIPTION
**Pull request by ttarczynski**
Goals:
- with more and more scripts it makes sense to generalize them
- reduce bash code duplication

### CODE REVIEW

**Comment by ttarczynski** [comment]
I have it ready for `kubernetes` provider.
Todo: use generic scripts for all other provders.

**Comment by ttarczynski** [comment]
Done:
* all examples use uniform `bin/apply.sh`, `bin/destroy.sh` scripts

**Comment by sanyer** [comment]
oh, it's in your fork
I was looking for a branch and almost reinstalled VSCode :-D

**Comment by sanyer** [comment]
Looks good, I don't have any questions

**Review by sanyer — APPROVED** [review]
Looks fine.
A really good first step in optimizing the scripts 👍🏻

**Comment by sanyer** [comment]
As the next improvements, we can look into the shared scripts and into apply and destroy scripts in each example. We might as well build some simple cli tool for this.

**Comment by ttarczynski** [comment]
I've just merged this into `integration` now.
To double check the CI.

**Comment by ttarczynski** [comment]
I've forced a complete test run on `integration` ([see this commit](https://github.com/ContainerSolutions/terraform-examples/commit/b865e838c1cacacca0b3d6e5b6efa1b8251ea7a6)). Was all OK, so merging this to `main`.

**Pull request merged**
